### ISSUE TITLE
실행 오류

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#105]
root@goorm:/workspace/Node(master)# node server
[경고!]: 시스템이 멀티 쓰레딩을 지원하지 않습니다
0.0.0.0:3000에서 실행 중. . .
/workspace/Node/functions.js:733
        if(skinconfig.override_views.includes(viewname)) {
                      ^

TypeError: Cannot read properties of undefined (reading 'override_views')
    at render (/workspace/Node/functions.js:733:16)
    at viewDocument (eval at <anonymous> (/workspace/Node/routes/router.js:29:5), <anonymous>:99:34)

**Comment by navyCarpet** [comment]
스킨 directory가 정확하게 일치하는지 확인해 보십시오.
폴더 이름이 skin이라면 작동하지 않음
