### ISSUE TITLE
라이선스 추가 건의

### ISSUE THREAD

**Issue by 24fw** [gdl-blue/imitated-seed-2#109]
https://github.com/gdl-blue/imitated-seed-2/issues/40#issuecomment-1637063285
 이럴때처럼 소스코드가 공개됬으면 하는때가 있는데 라이선스가 추가되면 어떨까합니다.

**Comment by navyCarpet** [comment]
nuxt 포팅을 못하겠으니 라이선스를 바꿔서 소스를 빼앗자는 뜻입니까?

**Comment by 24fw** [comment]
말이 왜그렇게 된건진 모르겠는데 더 나은 소스가 있을때 공개되면 좋겠다 이뜻입니다

**Comment by 24fw** [comment]
라이선스 없음의 이유가 있을거같네요
