### ISSUE TITLE
없는 문서(또는 이동되기 전 문서)가 임의 문서에서 뽑히는 오류

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#115]

**Comment by jeongjo13** [comment]
특정 시점에서 있었던 문서들은 있는 문서라고 판정되는 것 같습니다. 

이 이슈와 같은 원인으로 추정되는 문제가 더 있습니다.

- 존재하는 문서를 링크했을 때 링크가 파란색이어야 하는데 빨간색으로 표시되는 오류: 위 원인이 맞다면, 이 문제 역시 위에서 언급한 이유로 생기는 것 같습니다.

**Comment by navyCarpet** [comment]
없는 문서로 가는 리다이렉트가 있는지 확인해 보세요
