### ISSUE TITLE
계정이 해킹된 것 같습니다.

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#116]

**Comment by kepitrion** [comment]
어쩌다 문제가 발생했나요? 토론을 일괄적으로 삭제하는 코드는 없어 보이는데 권한 남용을 의심해 보시는 것이 좋을 듯 합니다.

**Comment by theseeduser** [comment]
계속 운영해봤는데 제 계정이 해킹되었나 보군요. 2023년 테스트위키 대사면이라고 되어있어서 일단 서버 닫았습니다.

**Comment by 24fw** [comment]
추측이긴한데 전에 공개된 db에서 오토로그인값 불러와서 로그인한것 아닐까요?

**Comment by theseeduser** [comment]
@24fw 비밀번호가 변경되어 있습니다.
