### ISSUE TITLE
리캡챠 오류

### ISSUE THREAD

**Issue by CordeliaDiv** [gdl-blue/imitated-seed-2#129]
안녕하세요. 저는 해당 엔진을 사용해서 작게 군소위키인 [루나위키](https://runa.wiki/)를 운영 중인 한 이용자입니다.
한가지 엔진에 사용함에 있어 버그가 있어 이렇게 이슈를 작성하게 되었습니다.
버그는 리캡챠를 바르게 작성하여도 틀렸다고 나옵니다.

**Comment by Jingdayeon** [comment]
추가로 문서 내용이 길면 서버가 다운되어 버립니다. 제 추측입니다만, 나무마크가 서버에 무리를 주는 것이 아닌가 싶습니다. 제 로컬 서버에서도 같은 문제가 일어나는 걸로 보아 엔진 코드 문제인거 같습니다.

**Comment by 24fw** [comment]
혹시 문서 글자수가 몇자인가요

**Comment by Jingdayeon** [comment]
> 혹시 문서 글자수가 몇자인가요
약 500자 ~ 1000자 정도에서 문제가 생겼던 걸로 판단됩니다.

**Comment by jeongjo13** [comment]
대충 1000자 쯤에서 해당 문제가 발생합니다.

**Comment by jeongjo13** [comment]
700자 정도였던 걸로 기억합니다

**Comment by CordeliaDiv** [comment]
리캡챠 오류 해결 확인되었습니다!
