### ISSUE TITLE
오류가 발생합니다

### ISSUE THREAD

**Issue by NOAH01112** [gdl-blue/imitated-seed-2#131]
cmd를 열고 node server를 했는데
내 도메인에서 실행 중. . .
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 122.32.20.86:80
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:2069:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRNOTAVAIL',
  errno: -4090,
  syscall: 'listen',
  address: '내 아이피',
  port: 80
}

Node.js v20.10.0
가 뜹니다.
현재 80번 포트 이용중인 프로그램 없습니다.

**Comment by 24fw** [comment]
80번포트대신 3000번포트처럼 다른포트를 사용하세요. 80번포트는 예약되어있는 포트입니다.

**Comment by NOAH01112** [comment]
> 다른 포트 사용하면 localhost:3000 이런식으로 들어가야 하지 않나요

**Comment by NOAH01112** [comment]
다른 포트 사용해도 똑같은 문제 발생합니다. 포트 문제가 아닌거 같습니다.

**Comment by 24fw** [comment]
그 내 ip부분을 127.0.0.1로 해보세요

**Comment by NOAH01112** [comment]
질문 있습니다.
1. 사용자:관리자 계정을 이용하고싶은데 어떻게 해야하나요
2. 로그인이 안됩니다.
3. 모든 문서 기본 ACL 어케 설정하나요
4. https 인증서 어케 적용하죠 crt파일 있습니다.

**Comment by NOAH01112** [comment]
5. 모방할 더시드엔진 버전 어케 설정하나요

**Comment by NOAH01112** [comment]
6. 기본이 FrontPage인걸 ??위키:대문으로 어떻게 바꾸나요

**Comment by 24fw** [comment]
6. /admin/config 에서 바꾸세요

**Comment by 24fw** [comment]
4. 클라우드플레어같은 서비스 이용하세요 crt적용법을 다 알려드릴수 없습니다

**Comment by 24fw** [comment]
5.
```
, "theseed_version": "x.y.z"
```
를 }뒤에 붙혀넣으세요
(x.y.z는 원하는 버전)

**Comment by NOAH01112** [comment]
/admin/config 들어갔더니 권한이 없다고 나오고 사용자 문서에 권한 있는데 특수권한 틀도 안뜨는데 어케하죠

**Comment by NOAH01112** [comment]
일단 서버를 돌리는 컴에선 로그인이 되는데 다른 기기에서는 다 입력해도 로그인이 안됩니다

**Comment by 24fw** [comment]
혹시 관리자 계정 id 뭘로하셨나요

**Comment by NOAH01112** [comment]
'관리자'로 했는데 config.json에서는 네모로 뜨던데요

**Comment by 24fw** [comment]
admin으로 새로가입하고 config.json도 admin으로 바꿔보세요

**Comment by NOAH01112** [comment]
네

**Comment by NOAH01112** [comment]
그리고 파일 올릴때 라이선스가 아무것도 안뜨는데 라이선스를 어디에 넣어야 뜨죠

**Comment by NOAH01112** [comment]
이메일인증 하고싶은데 보낼 이메일 어케 설정하나요

**Comment by 24fw** [comment]
readme 읽어보고 질문해주시길 바랍니다
