### ISSUE TITLE
이메일 허용 목록

### ISSUE THREAD

**Issue by CordeliaDiv** [gdl-blue/imitated-seed-2#132]
항상 수고가 많으십니다. 혹시 이메일 허용 목록 기능 추가 가능할까요?

**Comment by navyCarpet** [comment]
이미 있습니다.

**Comment by Jingzzinbbang** [comment]
> 이미 있습니다.

메일 허용을 키면 꺼지고 키면 꺼지는 것으로 보아 구현은 다 안된 것 같습니다
