### ISSUE TITLE
심각한 대괄호 파싱 오류

### ISSUE THREAD

**Issue by cylegagit** [gdl-blue/imitated-seed-2#14]
[테러 방지를 위해 숨겨짐]

**Comment by gdl-blue** [comment]
알고는 있습니다만 해결법을 아직 생각 중입니다.

**Comment by NaweGa** [comment]
(제 이론상으로는)안쪽부터 차례 차례 파싱하면 될 것 같기는 합니다.

**Comment by nawega** [comment]
제가 위키엔진 만드는 과정에서 해결책을 찾았는데, }}}는 모두 </div>로 변환하고, {{{는 <div style="어쩌고"로 하면 됩니다. {{{#ffffff 같은 경우에는 class를 추가해서  스타일과 별도로 display:inline을 추가하면 됩니다.
~~알려주기 아까운데...~~

**Comment by gdl-blue** [comment]
참고해서 고쳐보고 있습니다.

**Comment by gdl-blue** [comment]
일단 RAW에 있는 삼중 중괄호 개수가 일치하는지나 다른 여러 가지 검사해야 하는 것들도 있기도 하고 구현이 쉽지는 않을 것 같습니다.

**Comment by gdl-blue** [comment]
다른 나무마크 렌더러도 같이 참고해보면서 해보겠습니다.

**Comment by nawega** [comment]
> 다른 나무마크 렌더러도 같이 참고해보면서 해보겠습니다.

넹

**Comment by gdl-blue** [comment]
뭔가 확실한 방법이 생각났습니다. 구현 시도 중입니다

**Comment by gdl-blue** [comment]
해결 완료
