### ISSUE TITLE
config file, 스킨 외 2개 이슈 관련 

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#147]
- [x] **config.json 파일 복구** 부탁드립니다.
- [ ] **기본 스킨 liberty를 코드에 포함**시켜주시기 바랍니다.
- [ ] **자세한 설치법**을 알려주시기 바랍니다.

- [ ] sudo apt install npm, sudo apt upgrade npm을 했는데도 geoip-lite module 없다고 나옵니다. 어떻게 하나요? 우분투 최신 버전 사용 중

**Comment by solutionwiki** [comment]
클릭 미스.

**Comment by wikiengine** [comment]
개발자분이 리버티 스킨을 포함시켜버리면 GPL-3라이선스가 적용되야하기때문에 아마도 포함은 불가할거같습니다

**Comment by wikiengine** [comment]
geoip모듈 없다고나오는거는 위키 디렉터리 내에서
`npm i`
이 명령어 실행하셔야합니다

**Comment by wikiengine** [comment]
자세한 설치법 (ubuntu)
순서대로 터미널에 입력하세요.
`sudo apt update; sudo apt install nodejs; sudo apt install npm; sudo apt install git;` : apt업데이트, nodejs설치, npm설치, git설치
`git clone https://github.com/gdl-blue/imitated-seed-2; cd imitated-seed-2; mkdir css; mkdir skins; cd js; wget https://theseed.io/js/theseed.js https://theseed.io/js/jquery-2.1.4.min.js https://theseed.io/js/jquery-1.11.3.min.js https://theseed.io/js/intersection-observer.js https://theseed.io/js/dateformatter.js; cd ../css; wget https://theseed.io/css/wiki.css https://theseed.io/css/katex.min.css https://theseed.io/css/diffview.css; cd ../skins; git clone https://github.com/navyCarpet/imitated-skin-liberty.git liberty; cd ..; npm install` : 기본적인 설치방법, navycarpet님의 리버티를 사용
`node server` : 서버 초기세팅
`node server` : 서버 실행

**Comment by jeongjo13** [comment]
https://youtu.be/cZ3TeEcBXDI

제가 유튜브에 설치법 올려놓았습니다. 설치 시 도움이 되면 좋겠습니다. (검색으로는 안 뜨고 링크로만 접속 가능합니다.)
