### ISSUE TITLE
파일 서버

### ISSUE THREAD

**Issue by foxof4545** [gdl-blue/imitated-seed-2#15]
안녕하세요. 병아리엔진 잘 사용하고 있습니다.
그러나 현재 파일 올리기가 파일 서버가 사용이 불가능하다고 하네요
어떻게 파일 서버를 열어야 하나요?

**Comment by NaweGa** [comment]
파일 올리기는 미구현인걸로 알고있습니다.

**Comment by gdl-blue** [comment]
추후 구현할 예정입니다.

**Comment by cuprevenge** [comment]
외부 이미지 핫링크를 지원하는 건 어떨까요.

**Comment by gdl-blue** [comment]
틀:외부이미지
```{{{#!wiki style="background-image: url(@주소@); width: @width@px; height: @height@px; display: inline-block;"
}}}```
이렇게 하면 될 것 같습니다. 예전에 알파위키에서도 한번 썼던 적이 있습니다. (아 예전 알파위키 추억이네요...)

**Comment by gdl-blue** [comment]
```
[include(틀:외부이미지, 주소=https://cdn.discordapp.com/attachments/897985811029581844/1014851315471503420/56d51695cd58d3b4.png, width=556, height=421)]
```

**Comment by nawega** [comment]
파일 서버 개발하실 때, 따로 분리하시는 것이 좋겠습니다. (the seed와 같이) 외부 이미지 캐싱도 파일 서버에서 처리하고요.(접속 수 체크해서 캐싱 처리 안했다가 imgur과 나무위키 꼴 납니다.)

**Comment by gdl-blue** [comment]
그건 그렇게 하려고 하고 있습니다. 틀로 만든 외부 이미지는 엔진 정식 기능이라기기보다는 그냥 임시 꼼수에 가깝습니다. 알파위키에서도 재개장 때 화일 올리기가 안 돼서 임시로 썼던 방법이기도 하고 관련 안내문에서도 호스팅이 허기된 곳인지 꼭 확인하라고 하고 있습니다.

**Comment by poiega** [comment]
> 파일 서버를 만드는 것은 그렇게 하려고 하고 있습니다.
> 
> 틀로 만든 외부 이미지는 엔진 정식 기능이라기기보다는 그냥 임시 꼼수에 가깝습니다. 알파위키에서도 재개장 때 화일 올리기가 안 돼서 임시로 썼던 방법이기도 하고 관련 안내문에서도 호스팅이 허기된 곳인지 꼭 확인하라고 하고 있습니다.

허기에서 허가로 수정부탁드리고, 기기 기로 수정해주요
