### ISSUE TITLE
가입인증 이메일 타사메일로 안보내짐

### ISSUE THREAD

**Issue by NOAH01112** [gdl-blue/imitated-seed-2#157]
다음메일을 사용하려고 mailhost를 smtp.daum.net으로 설정하고 보낼 이메일과 다음메일 비밀번호를 입력했더니
node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

Error: getaddrinfo ENOTFOUND stmp.daum.net
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
  errno: -3008,
  code: 'EDNS',
  syscall: 'getaddrinfo',
  hostname: 'stmp.daum.net',
  command: 'CONN'
}
해당 오류가 뜹니다.

**Comment by NOAH01112** [comment]
다음은 config.json 파일 중 일부입니다.
"mailhost":"stmp.daum.net","email":"piwiki@plground.xyz","passwd":"비밀번호(가림)"

**Comment by wikiengine** [comment]
메일주소가 정확한가요?

**Comment by NOAH01112** [comment]
네 정확합니다.

**Comment by NOAH01112** [comment]
설마 스마트워크 이메일은 안되는건가요..?

**Comment by NOAH01112** [comment]
적어도, 빼도 똑같은 오류가 발생합니다.

**Comment by NOAH01112** [comment]
네

**Comment by wikiengine** [comment]
pr 받아지면 한번 적용해보시고 안되시면 말해주세요

**Comment by NOAH01112** [comment]
그..게.. 뭐죠..?

**Comment by wikiengine** [comment]
이 리포에 제가올린 pullrequest가 받아들여지면 위키엔진 업데이트 해보라는말입니다

**Comment by wikiengine** [comment]
업데이트 적용해보세요

**Comment by NOAH01112** [comment]
수정 완료
