### ISSUE TITLE
버그 제보

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#171]
![20240226_075600](https://github.com/gdl-blue/imitated-seed-2/assets/128890349/1878a4ff-deda-4f90-ab11-582e34e0f2d2)
위와 같이 편집 요청을 승인한 사용자(요청한 사용자 x)가 차단되었을시 취소선이 그어지는 버그가 있습니다. 나무위키에서 봤는데 편집 요청을 승인한 사용자는 차단되어도 취소선이 그어지지 않습니다.

**Comment by theseeduser** [comment]
그리고 1분 차단했는데 지금도 취소선이 그어져 있습니다.

**Comment by jeongjo13** [comment]
차단내역에서 실행자 사용자명에도 취소선 안 그어집니다. 이 부분도 수정 부탁드립니다.
