### ISSUE TITLE
문의

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#175]
nuxt판 엔진은 지금도 개발 중이신가요? test님이 소스 코드를 공개할 '생각'이 있다고 하셨고 지금까지 공개하지 않으셔서 해당 엔진은 공개되지 않을 것 같습니다.

그리고 구름ide가 사용량 기반 요금제로 바뀌었는데 대체용으로 codesandbox 추천드립니다.

**Comment by wikiengine** [comment]
test님버전 nuxt프론트엔드는 병아리엔진 내용을 그대로 가져와서 nuxt에서 보여주는방식으로 알고있습니다. the seed엔진처럼 구현하기위해선 병아리를 api화시켜서 nuxt2에서 api를 불러와서 렌더링하는방식으로 제작해야합니다. 오래걸릴거같습니다

**Comment by theseeduser** [comment]
확인했습니다.
