### ISSUE TITLE
센카와

### ISSUE THREAD

**Issue by CordeliaDiv** [gdl-blue/imitated-seed-2#182]
옛날에 gdl-blue님께 배포 받은 센카와 스킨을 이용해서 더위키 센카와 처럼 커스텀 할려는데 커스텀 해도 될까요? 또, 커스텀 후에 위키에 적용해도 될까요?

**Comment by wikiengine** [comment]
커스텀을 한다고해도 원본의 저작권은 umanle에 있습니다. 제가 저작권자는 아닙니다만 개인적인 사용(gdl-blue님처럼)외에는 다른 공개적인 사이트에서 사용하는것은 지양하시는게 맞는거같습니다. 참고로 senkawa_2018같은 스킨은 모방스킨이 아니고 senkawa스킨 렌더링본을 swig적용시킨버전입니다.

**Comment by CordeliaDiv** [comment]
그렇군요 알겠습니다.

**Comment by CordeliaDiv** [comment]
> 센카와 스킨 조금 더 버그 수정해서 기존 나무위키와 거의 동일하게 만들었는데 보내드릴까요?

그래 주시면 감사드리겠습니다.

cordelia@testwiki.kr

**Comment by CordeliaDiv** [comment]
감사합니다

**Comment by CordeliaDiv** [comment]
이 질문에 대해 새로 질문합니당

이번에 senkawa 스킨을 기반으로 새로운 디자인의 스킨을 만들려고 합니다. 만든 후 배포해도 될까요? 원본 코드에 대한 출처는 남기겠습니다.
