### ISSUE TITLE
문서 생성 오류

### ISSUE THREAD

**Issue by dve1** [gdl-blue/imitated-seed-2#184]
문서를 생성할 때, 새 문서 만들기를 누르면 일부 문서는 문서를 찾을 수 없다는 오류가 나옵니다.

**Comment by jeongjo13** [comment]
편집 권한이 없어 편집 요청으로 넘어갔는데 없는 문서는 편집 요청이 안되기 때문에 해당 오류가 발생하는 것 같습니다.
