### ISSUE TITLE
관리자 오류

### ISSUE THREAD

**Issue by dve1** [gdl-blue/imitated-seed-2#185]
버전을 4.22.7로 설정하였고, 관리자 관한을 부여해도 역사 숨기기와 편집 요약 숨기기가 보이지 않습니다.

**Comment by theseeduser** [comment]
역사 숨기기는 소유자 권한이 필요합니다.
편집 요약 숨기기는 hide_document_history_log 권한이 필요합니다.

**Comment by dve1** [comment]
소유자 권한을 어떻게 부여하나요?

**Comment by dve1** [comment]
hide_document_history_log 권한 부여했습니다. 그래도 안됩니다.

**Comment by dve1** [comment]
dksldh

**Comment by dve1** [comment]
아니오

**Comment by dve1** [comment]
넵 감사합니다. 이슈 닫습니다.
