### ISSUE TITLE
나무마크 버그

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#191]
원래 잘 작동됬는데 갑자기 이러네요.[* 4면의 끝 사이 간격이 좁습니다.]
[[https://testwiki.kr/w/%EC%82%AC%EC%9A%A9%EC%9E%90%3Atheseeduser]]

**Comment by NOAH01112** [comment]
토론에서도 그러네요

**Comment by NOAH01112** [comment]
![image](https://github.com/gdl-blue/imitated-seed-2/assets/93462843/2aa1dd44-c9a3-417b-bc11-05fae35fe2cc)

**Comment by theseeduser** [comment]
링크 수정: https://testwiki.kr/w/%E3%85%8C%E3%85%85%E3%85%8C
