### ISSUE TITLE
차단 내역

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#194]
차단시 차단 내역에서도 취소선이 쳐집니다.
![Uploading Screenshot_20240229_094034_Chrome.jpg…]()

**Comment by yoojinwoo12** [comment]
![Uploading Screenshot_20240229_094034_Chrome.jpg…]()

**Comment by yoojinwoo12** [comment]
![Screenshot_20240229_094138_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/63dc50b8-e0be-4862-982e-1bdd90e1bfd1)

**Comment by jeongjo13** [comment]
아직 소유자님께서 업데이트를 안 하신 것 같습니다.
