### ISSUE TITLE
파일을 올렸을때 오류가 납니다.

### ISSUE THREAD

**Issue by somewikiuser** [gdl-blue/imitated-seed-2#198]
413 Request Entity Too Large
라는 오류가 납니다. 고쳐주시면 감사드리겠습니다.

**Comment by navyCarpet** [comment]
파일 용량을 줄이세요

**Comment by somewikiuser** [comment]
![IMG_5737](https://github.com/gdl-blue/imitated-seed-2/assets/142154781/b56788e3-26cd-4681-8bff-c33f7f8bcd38)
대충 이거긴 한데.. 지금 모바일이라 몇메간지는..
