### ISSUE TITLE
admin/config 페이지 로딩 안됨

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#199]
기본페이지를 변경할려고 admin/config 페이지에 접속할려는데 비로그인 상태에서는 접속되는데 로그인한 상태에서는 접속이 안됩니다.

어떻게 해야 하나요?

**Comment by BeepSheep10** [comment]
> 터미날에 어떤 종류의 편지를 보내시겠습니까?
터미널에 오류는 뜨지 않고 접속이 안됩니다.

**Comment by BeepSheep10** [comment]
터미널에 오류는 안뜨고 걍 접속자체가 안됩니다.

**Comment by BeepSheep10** [comment]
> 터미날에 어떤 오류가 뜹니까?
터미널에는 오류 안뜨고 정상작동하며 접속이 안됩니다.

**Comment by BeepSheep10** [comment]
> 터미날에 어떤 오류가 뜹니까?
glitch로 위키를 운영하고 있습니다.

**Comment by BeepSheep10** [comment]
{"host":"0.0.0.0","port":"3000","skin":"liberty","search_host":"127.5.5.5","search_port":"25005","file_host":"127.5.5.5","file_port":"27775","disable_file_server":false,"owners":["BeepSheep"],"disable_email":true,"sessionhttps":"true","use_external_js":"true","use_external_css":"true","owners":"BeepSheep","search_autostart":"true","custom_namespaces":"스타위키","theseed_version":"4.22.8"}
config.json에는 이렇게 되있습니다.

**Comment by wikiengine** [comment]
owners가 두개인데 한번 빼보세요

**Comment by navyCarpet** [comment]
glitch는 터미널이 아니라 로그를 봐야합니다.

**Comment by BeepSheep10** [comment]
배열 형태로 했는데도 접속이 안됩니다.
