### ISSUE TITLE
세션 아이디 관련

### ISSUE THREAD

**Issue by nawega** [gdl-blue/imitated-seed-2#20]
[알파위키 대피소](https://yopu.xyz)에서 세션 아이디가 페이지 이동시마다 바뀝니다;;;

**Comment by nawega** [comment]
@gdl-blue 중요한 문제이므로 맨션합니다

**Comment by nawega** [comment]
네. Ajax든, 페이지 이동이든 새 요청을 보낼 때 마다 세션 아이디가 바뀝니다.

**Comment by gdl-blue** [comment]
정확한 원인은 모르겠으나, 자동 로그인을 켜고 로그인해보십시오.

**Comment by nawega** [comment]
클라우드플레어 Ddos Protection 모드가 겨진 이후 생긴 오류로 보이니 클플 문제일 수도 있겠습니다.

**Comment by nawega** [comment]
https://user-images.githubusercontent.com/104440972/190884887-7e1df76a-4b23-41da-af2a-62a65eecefa7.mp4

**Comment by nawega** [comment]
관련 영상 첨부합니다.

**Comment by gdl-blue** [comment]
반달을 해도 디도스 공격을 하는 경우는 그렇게 자주 있지는 않은데 디도스 보호모드를 꺼도 무방하시겠습니까?

**Comment by nawega** [comment]
요푸님이 매크로를 막기 위해 켜놓으셨다고 하셨습니다. 제가 아니라 요푸님께 문의해 주시는게 좋을 듯 합니다.
