### ISSUE TITLE
admin/config 페이지 로딩 안됨

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#201]
gdl-blue님이 말씀하신것처럼 owner를 제거하고
배열형태로 만들었는데 그래도 접속이 안됩니다 .

{"host":"0.0.0.0","port":"3000","skin":"liberty","search_host":"127.5.5.5","search_port":"25005","file_host":"127.5.5.5","file_port":"27775","disable_file_server":false,"owners":["BeepSheep"],"disable_email":true,"sessionhttps":"true","use_external_js":"true","use_external_css":"true","search_autostart":"true","custom_namespaces":"스타위키","theseed_version":"4.22.8"}

**Comment by navyCarpet** [comment]
> > 터미날에 어떤 오류가 뜹니까?
> > 터미널에는 오류 안뜨고 정상작동하며 접속이 안됩니다.

glitch는 터미널이 아니라 로그를 봐야합니다.

**Comment by BeepSheep10** [comment]
> > > 터미날에 어떤 오류가 뜹니까?
> > > 터미널에는 오류 안뜨고 정상작동하며 접속이 안됩니다.
> 
> glitch는 터미널이 아니라 로그를 봐야합니다.

로그에 이렇게 적혀있습니다.

**Comment by navyCarpet** [comment]
glitch 주소를 알려주실 수 있나요?

**Comment by BeepSheep10** [comment]
https://glitch.com/edit/#!/starwiki?path=config.json%3A1%3A236 입니다.

**Comment by navyCarpet** [comment]
custom_namespaces는 Array 형태여야 합니다.

**Comment by navyCarpet** [comment]
> > > > 터미날에 어떤 오류가 뜹니까?
> > > > 터미널에는 오류 안뜨고 정상작동하며 접속이 안됩니다.
> > 
> > 
> > glitch는 터미널이 아니라 로그를 봐야합니다.
> 
> 로그에 이렇게 적혀있습니다.

그리고 UnhandledPromiseRejectionWarning: TypeError: (hostconfig.custom_namespaces || []).join is not a function 로그에 에러가 뜨는데 안뜬다고 하시면 도와드리기가 어렵습니다.
