### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#209]
차단기간이 만료되면 취소선이 없어지지않는 버그가 있는듯 합니다.

**Comment by solutionwiki** [comment]
liberty 본인입니다

네. 안 없어집니다.

**Comment by jeongjo13** [comment]
이 버그는 파이위키에서 발생하였으며, 이전에 이 버그를 수정하는 패치 이후 파이위키는 아직 엔진 업데이트를 안 한 걸로 알고 있습니다.

따라서 엔진 업데이트를 먼저 해봐야 할 것 같습니다.
