### ISSUE TITLE
리캡챠 버그 발생

### ISSUE THREAD

**Issue by yopu1230** [gdl-blue/imitated-seed-2#21]
리캡챠에 올바른 문자를 입력하여도" 리캡챠 인증에 실패했습니다."라는 오류가 발생합니다.

**Comment by gdl-blue** [comment]
보안문자가 쿠키를 써서 돌아가는데, 클라우드 플레어 디도스 방어 기능에서 쿠키를 이상하게 바꿔버리는 현상이 있습니다. 위키에 반달이 많아도 디도스 공격을 해서 접속을 못하게 하는 경우는 많지 않습니다. 꼭 디도스 방어 기능이 필요하지 않다면 끌 것을 추천하며, 끄고 나서 로그인이 계속 풀리거나 스킨이 바뀌는 현상도 해결될 것입니다.

**Comment by yopu1230** [comment]
확인하였습니다. 감사합니다.

**Comment by yopu1230** [comment]
Under Attack Mode 비활성화 후에도 여전히 오류가 계속됩니다.

**Comment by gdl-blue** [comment]
![image](https://user-images.githubusercontent.com/55873929/191032987-5ddcf0da-5f66-48c1-adaa-4c10314f70d0.png)


지금 사이트에 들어가지지 않는 것 같아요.

**Comment by gdl-blue** [comment]
> Under Attack Mode 비활성화 후에도 여전히 오류가 계속됩니다.

https://github.com/gdl-blue/imitated-seed-2/issues/20
> nawega: 클라우드플레어 Ddos Protection 모드가 겨진 이후 생긴 오류로 보이니 클플 문제일 수도 있겠습니다.

제가 클라우드 플레어를 안 써봐서 그렇습니다만, 위의 디도스 보호모드랑 Under Attack Mode가 다릅니까?

**Comment by yopu1230** [comment]
> Owner

디도스 방어 모드가 Under Attack Mode입니다.

**Comment by yopu1230** [comment]
이유를 알 수 없는 문제였나 봅니다. 재설치하니 해결되었습니다.
