### ISSUE TITLE
ACL그룹

### ISSUE THREAD

**Issue by NOAH01112** [gdl-blue/imitated-seed-2#212]
ACL그룹에서 가입 불가를 체크해도 가입이 됩니다.

**Comment by NOAH01112** [comment]
ACL그룹 생성할때

**Comment by solutionwiki** [comment]
맞습니다

**Comment by yoojinwoo12** [comment]
[오류!] 이용중인 IP는 문서 훼손행위가 자주 발생하는 IP이므로 로그인이 필요합니다.
(이 메세지는 본인이 반달을 했다기 보다는 해당 통신사를 쓰는 다른 누군가가 해서 발생했을 확률이 높습니다.)

이 문구가 안뜨나요? 가입버튼 누르면 뜹니다.

**Comment by NOAH01112** [comment]
정상적으로 회원가입이 가능합니다. 그리고 다음에서 스마트워크 이메일로 인증메일 발송하는데 gmail로 발송이 안됩니다.

**Comment by wikiengine** [comment]
다른 메일 서비스로는 발송이 가능한가요

**Comment by NOAH01112** [comment]
네 가능합니다

**Comment by wikiengine** [comment]
스마트워크측 문제인거같은데 다른서비스로 바꾸시는게 어떠신가요

**Comment by NOAH01112** [comment]
혹시 PR은 어떻게 쓰나요

**Comment by yoojinwoo12** [comment]
어떤 위키에서 그란가요?

**Comment by NOAH01112** [comment]
파이위키요

**Comment by yoojinwoo12** [comment]
잘 차단 되던데요?

**Comment by yoojinwoo12** [comment]
혹시 IPv6를 다른 사이트에서 조회해서 가져와 차단하신건가요?
그렇게 되면 안됩니다.

**Comment by NOAH01112** [comment]
아뇨 그냥 ipv4 했는데요

**Comment by yoojinwoo12** [comment]
저는 잘 차단이 되었습니다.

**Comment by NOAH01112** [comment]
희한하네요..
