### ISSUE TITLE
파일 올리는법

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#213]
안녕하세요. 파일을 올리려고 하는데
라이선스와 분류 목록에 아무것도 뜨지 않습니다.

glitch에서 뭘 입력해야 하나요?
https://starwiki.glitch.me/Upload

**Comment by navyCarpet** [comment]
이런 문의는 한번 찾아보고 올리시길 바랍니다

**Comment by navyCarpet** [comment]
틀:이미지 라이선스/*
분류:파일/*

답변하자면 위와 같은 형식의 문서를 생성하셔야 뜹니다.
