### ISSUE TITLE
이메일 인증 설정 관련

### ISSUE THREAD

**Issue by yopu1230** [gdl-blue/imitated-seed-2#22]
/admin/config 에서는 이메일 인증 기능을 설정하기 위해 필요한 옵션이 표시되지 않습니다. 혹시 이메일 인증 기능을 설정하는 방법을 알 수 있을까요?

**Comment by nawega** [comment]
미구현 이거나 node 내부(PHP mail 함수처럼) 함수를 이용하는 것으로 추정됩니다.

**Comment by gdl-blue** [comment]
아직 구현되지 않았습니다.

**Comment by yopu1230** [comment]
확인하였습니다. 감사합니다.

**Comment by gdl-blue** [comment]
아직 전자우편 인증, 렌더러의 각주 등 안 되는 부분이 있기도 하고 디시인사이드 두표에서도 오픈나무가 더 많게 나오기도 했고... 실제 위키 운영에 필요한 기능들이 다 만들어지기 전까지는 저도 오픈나무를 추천하긴 합니다. 지금은 없앴지만 3년 전에도 저는 오픈나무를 개조해서 더 시드 모방 엔진을 지금 이 imitated-seed 수준으로 만들었기도 했는데 오픈나무의 구조적인 문제인 "동기 방식"인 것(여러 사람이 접속하는 사이트에서는 사용되어서는 안 됩니다.)과 다른 몇몇 이유로 버렸죠.
