### ISSUE TITLE
업데이트 관련

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#226]
`git pull -f origin master` 해도 4.22.9 버전이 안 뜨는데 의도된 사항인가요?

**Comment by somewikiuser** [comment]
config.json에서 직접 업데이트 하셔야 할 것 같습니다.("theseed_version":"4.22.9")
현재 엔진 내부에서는 더 시드 4.22.7 버전까지 업데이트가 가능합니다.

**Comment by solutionwiki** [comment]
확인했습니다.
