### ISSUE TITLE
엔진 내부에서 4.22.9까지 업그레이드

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#228]
admin/config 라우트에서 내부적으로 업데이트 가능하도록

**Comment by solutionwiki** [comment]
지금도 4.22.x 기능이 있는데 그럼 그건 왜 있을까요?

**Comment by wikiengine** [comment]
아 한동안 이위키엔진 안건드려서 몰랐네요
./routes/config.js에
`
${tsver('4.22.9')}
`
추가해보세요

**Comment by solutionwiki** [comment]
확인
