### ISSUE TITLE
토론 #n

### ISSUE THREAD

**Issue by cuprevenge** [gdl-blue/imitated-seed-2#23]
![image](https://user-images.githubusercontent.com/52319594/191333205-992bfec2-79a6-47ce-bc26-57f8f7aa8e88.png)

토론에서 #1 #2 식으로 연달아서 사용할 경우 후자에는 링크가 걸리지 않는 듯 합니다.

**Comment by nawega** [comment]
지금 할 수 있는 대응방안은 [[#1]] [[#2]] 형식입니다.

**Comment by gdl-blue** [comment]
나중에 고쳐보겠습니다

**Comment by gdl-blue** [comment]
해결했습니다
