### ISSUE TITLE
엔진 업데이트 방법

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#237]
안녕하세요 엔진 업데이트는 어떻게 하는지
여쭤봅니다.

**Comment by somewikiuser** [comment]
gut pull 치세요

**Comment by somewikiuser** [comment]
수정된 파일은 git add로 넣으시고요

**Comment by BeepSheep10** [comment]
> 수정된 파일은 git add로 넣으시고요
제 위키는 글리치 서버로 운영중인데
글리치에서도 되나요?
