### ISSUE TITLE
실행 오류

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#242]
![스크린샷 2024-03-17 183723](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/a7466d7b-7a44-4db7-9f08-bc372d450c17)

**Comment by yoojinwoo12** [comment]
실행을 하면 이런 문구가 뜨면서 안됩니다.

**Comment by somewikiuser** [comment]
리버티 스킨에 config.json이 없다네요

**Comment by NOAH01112** [comment]
대충 config.json 파일 만드시고 안에
{
	"override_views": [],
	"static_files": [
		"css/font-awesome.min.css",
		"bootstrap/css/bootstrap.min.css",
		"css/font/Noto Sans KR.css",
		"css/default.css",
		"css/default_mobile.css",
		"css/theseed.css",
		"css/jquery-ui.min.css",
		"js/lib/bootstrap.min.js",
		"js/lib/jquery-ui.min.js",
		"js/live_Recents.js",
		"js/layout.js",
		"js/theseed.js"
	],
	"auto_js_targets": {
		"*": [
			{
				"path": "js/lib/bootstrap.min.js"
			},
			{
				"path": "js/lib/jquery-ui.min.js"
			},
			{
				"path": "js/live_Recents.js"
			},
			{
				"path": "js/layout.js"
			},
			{
				"path": "js/theseed.js"
			}
		]
	},
	"auto_css_targets": {
		"*": [
			"css/font-awesome.min.css",
			"bootstrap/css/bootstrap.min.css",
			"css/font/Noto Sans KR.css",
			"css/default.css",
			"css/default_mobile.css",
			"css/jquery-ui.min.css",
			"css/theseed.css"
		]
	},
	"manual_file_targets": {},
	"body_classes": [
		"Liberty"
	],
	"additional_heads": "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">"
}
넣어보세요.

**Comment by solutionwiki** [comment]
cd skins
cd theseed-skin-liberty
nano config.json

**Comment by yoojinwoo12** [comment]
> 대충 config.json 파일 만드시고 안에 { "override_views": [], "static_files": [ "css/font-awesome.min.css", "bootstrap/css/bootstrap.min.css", "css/font/Noto Sans KR.css", "css/default.css", "css/default_mobile.css", "css/theseed.css", "css/jquery-ui.min.css", "js/lib/bootstrap.min.js", "js/lib/jquery-ui.min.js", "js/live_Recents.js", "js/layout.js", "js/theseed.js" ], "auto_js_targets": { "_": [ { "path": "js/lib/bootstrap.min.js" }, { "path": "js/lib/jquery-ui.min.js" }, { "path": "js/live_Recents.js" }, { "path": "js/layout.js" }, { "path": "js/theseed.js" } ] }, "auto_css_targets": { "_": [ "css/font-awesome.min.css", "bootstrap/css/bootstrap.min.css", "css/font/Noto Sans KR.css", "css/default.css", "css/default_mobile.css", "css/jquery-ui.min.css", "css/theseed.css" ] }, "manual_file_targets": {}, "body_classes": [ "Liberty" ], "additional_heads": "<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">" } 넣어보세요.

어디에 만들고 넣어야 하나요?

**Comment by yoojinwoo12** [comment]
추가로 css는 어디서 가져오나요?

**Comment by yoojinwoo12** [comment]
> 대충 config.json 파일 만드시고 안에 { "override_views": [], "static_files": [ "css/font-awesome.min.css", "bootstrap/css/bootstrap.min.css", "css/font/Noto Sans KR.css", "css/default.css", "css/default_mobile.css", "css/theseed.css", "css/jquery-ui.min.css", "js/lib/bootstrap.min.js", "js/lib/jquery-ui.min.js", "js/live_Recents.js", "js/layout.js", "js/theseed.js" ], "auto_js_targets": { "_": [ { "path": "js/lib/bootstrap.min.js" }, { "path": "js/lib/jquery-ui.min.js" }, { "path": "js/live_Recents.js" }, { "path": "js/layout.js" }, { "path": "js/theseed.js" } ] }, "auto_css_targets": { "_": [ "css/font-awesome.min.css", "bootstrap/css/bootstrap.min.css", "css/font/Noto Sans KR.css", "css/default.css", "css/default_mobile.css", "css/jquery-ui.min.css", "css/theseed.css" ] }, "manual_file_targets": {}, "body_classes": [ "Liberty" ], "additional_heads": "<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">" } 넣어보세요.

붙여넣기는 어떻게하나요?

**Comment by solutionwiki** [comment]
github로 업로드 한 다음에 클론해보세요

**Comment by somewikiuser** [comment]
.. 그냥 오른쪽 키 누르세요 안되면 오른쪽 키 누르고 붙여넣기 하시거나

**Comment by solutionwiki** [comment]
우분투 서버 도스라 그게 안됩니다..
(VM)

**Comment by somewikiuser** [comment]
그냥 입력하시던가요..
