### ISSUE TITLE
글리치에서 엔진 업데이트 방법

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#246]
제 위키가 글리치 서버로 운영중인데
글리치에서 엔진 업데이트를 우예 하나요?

지난 이슈에서 솔루션위키님께서 git pull -f origin master
를 콘솔 입력이라고 하셨는데

글리치에서 콘솔이 어디있나요?
터미널에다가 입력하면 되나요?

**Comment by wikiengine** [comment]
콘솔이 터미널입니다
