### ISSUE TITLE
글리치 엔진 업데이트 오류

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#247]
글리치에서 엔진 업데이트 하려고 
터미널에  git pull -f origin master를 입력했는데 
오류가 떳습니다.
무슨 문제길래 오류가 뜬걸까요?
![Screenshot_20240321_132437_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/161922404/0456ca0d-9c06-41d9-add1-ab00780f0747)

**Comment by navyCarpet** [comment]
구글에 검색해 보세요
