### ISSUE TITLE
Glitch로 엔진 업데이트 방법

### ISSUE THREAD

**Issue by BeepSheep10** [gdl-blue/imitated-seed-2#248]
Glitch로 엔진 업데이트 하는 방법좀 알려주세요!
git pull -f origin master를 터미널에다가 입력하라고 하는데 이런 오류가 떠서 업데이트가 안됩니다.
![Screenshot_20240321_132437_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/161922404/75ec07b9-949d-44a7-b32b-b77877340987)

**Comment by navyCarpet** [comment]
구글에 검색해 보세요
