### ISSUE TITLE
[스킨 테스트 필요] Liberty 테마: IPACL과 ACLGroup 동시 핸들링

### ISSUE THREAD

**Issue by JeonDohyeon** [gdl-blue/imitated-seed-2#25]
https://github.com/JeonDohyeon/theseed-skin-liberty/tree/test/combined/aclgroup-and-ipacl
^^ 이걸로 보세요 (방금 확인함)

[기존]/old
소스는 https://github.com/JeonDohyeon/theseed-skin-liberty 에서 대충 보시면 됩니다
써도 돼요 쓰라고 만든 거니까
쓸땐 `aclgroup` 브랜치 기준으로 포크해서 쓰시면 됩니다
~~ipacl 권한이랑 aclgroup 권한이 같은 레벨이라 가능한 수정이었... 허헣~~ 다르네요 ㅋㅋㅋ ipacl에서 aclgroup으로 바꿔야겠다

사실 이거가 따로 말할 데가 따로 없는 거 같아서 올린거라
아마 며칠 뒤에 닫을 예정입니다

..아마도?

**Comment by gdl-blue** [comment]
잘하셨습니다

**Comment by JeonDohyeon** [comment]
++업데이트++
[새 브랜치](https://github.com/JeonDohyeon/theseed-skin-liberty/tree/test/combined/aclgroup-and-ipacl)에 테스트용으로 올렸습니다.
차이 보기: [여기](https://github.com/JeonDohyeon/theseed-skin-liberty/commit/4c923622ebb899c3021582f3dc94fd46219332ce)
일단 제가 최신 버전의 node를 쓰긴 하는데, 기존 버전에서 [`aclgroup` 브랜치](https://github.com/JeonDohyeon/theseed-skin-liberty/tree/aclgroup)가 오류가 없었어서
얘도 겹쳐진 if문만 핸들링이 되면 작동할 거라 봅니다.

++기존 버전 Known Issues++
- ACLGroup이 `perm:aclgroup`을 가진 분에게 표시되지 않음
  + 해결법: `{%if perm.has('ipacl') %}`를 `{%if perm.has('aclgroup') %}`으로 정정하여 사용하시면 됩니다.
  통합 브랜치에선 해결했습니다.

**Comment by JeonDohyeon** [comment]
이슈 닫고 새걸로 다시 열게요
작업 2개 더 함..ㅋㅋㅋ
