### ISSUE TITLE
사이트가 이상합니다.

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#252]
서버는 열렸는데 이렇게나옵니다.
![Uploading 20240323_182221.jpg…]()
###

**Comment by yoojinwoo12** [comment]
![20240323_182221](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/7b7e7049-1b39-4c9e-8ead-59893da206b3)

**Comment by navyCarpet** [comment]
스킨을 제대로 넣으세요

**Comment by yoojinwoo12** [comment]
그리고 css는 어디서 가져오나요?

**Comment by navyCarpet** [comment]
구글에 검색해 보세요

**Comment by SomniumDev** [comment]
그냥 config.json에 use_ex어쩌구 js랑 use_ex 어쩌구 css 넣으세요

**Comment by solutionwiki** [comment]
nano config.json
"use_external_css": true,"use_external_js": true

**Comment by yoojinwoo12** [comment]
![17112608572361195872237245129574](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/971b01bf-660f-4ede-8494-9b012d5ba57c)

왜 ACLGROUP이 안뜨는지 알수 있을까요?

**Comment by SomniumDev** [comment]
더시드 버전을 올리시고

**Comment by yoojinwoo12** [comment]
> 더시드 버전을 올리시고

@SomniumDev 

4.22.9로 해도 표시가 안됩니다.

**Comment by NOAH01112** [comment]
어떻게 뜨시는데요

**Comment by NOAH01112** [comment]
라이선스 페이지와 함께 도구를 클릭하신 후 보여주세요

**Comment by SomniumDev** [comment]
버전 내리시고 ipacl, suspend_account 회수하세요

**Comment by SomniumDev** [comment]
그다음에 다시 올리세요
