### ISSUE TITLE
Ubuntu 설치법

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#253]
sudo apt update; sudo apt install nodejs; sudo apt install npm; sudo apt install git; git clone https://github.com/gdl-blue/imitated-seed-2; cd imitated-seed-2; mkdir css; mkdir skins; cd js; wget https://theseed.io/js/theseed.js https://theseed.io/js/jquery-2.1.4.min.js https://theseed.io/js/jquery-1.11.3.min.js https://theseed.io/js/intersection-observer.js https://theseed.io/js/dateformatter.js; cd ../css; wget https://theseed.io/css/wiki.css https://theseed.io/css/katex.min.css https://theseed.io/css/diffview.css; cd ../skins; git clone https://github.com/navyCarpet/imitated-skin-liberty.git liberty; cd ..; sudo apt install npm; node server

**Comment by yoojinwoo123** [comment]
https://github.com/navyCarpet/imitated-skin-liberty.git
이 스킨을 쓰면 로고 적용이 안되는데 어떻게하나요?

**Comment by SomniumDev** [comment]
로고 적용 됩니다.
