### ISSUE TITLE
교집합 acl 설정

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#257]
https://haneul.wiki/thread/AcceptableLoudOpenMouse#43
교집합으로 ACL 설정할 수 있게 개발 부탁드립니다 :)

**Comment by solutionwiki** [comment]
예를 들면 perm:match_username_and_document_title AND aclgroup:인증된 사용자

그리고 perm:document_contributor AND member_signup_15days_ago

**Comment by somewikiuser** [comment]
원본 엔진에 해당 기능이 있나요?
