### ISSUE TITLE
theseed-version="1.18.0"에서 aclgroup에 사용자/ip 추가, 삭제 안 됨

### ISSUE THREAD

**Issue by JeonDohyeon** [gdl-blue/imitated-seed-2#26]
* 빠른 접근을 위해 개조한 스킨을 사용하고 있습니다. 그래봤자 그냥 링크만 주는 거라 의미는 없음.
* IIS 10.0에서 돌리고 있습니다. 정작 IIS에서 인식하는 디렉토리엔 `web.config` 파일 하나만 있고 앱은 따로 돌리는 중.

[![Screenshot_20221014_110559_Chrome](https://user-images.githubusercontent.com/34373595/195745389-ae658b02-5c00-45d4-b778-8132beef05d2.png)](http://wiki.jdh5968.pe.kr:8800/aclgroup)
위 스샷과 같이, ACLGroup 화면을 표시하고 있는 상태에서 ACLGroup 설정이 불가합니다.
그룹이 표시되고 그 그룹을 선택해 하위에 ACLGroup을 설정하는 방식인 걸로 보이는데
( https://namu.wiki/aclgroup, https://theseed.io/aclgroup 참조)
\[추가\]를 백날 눌러도 아무런 반응이 없습니다.

별도로 설정하는 방법이 있는 건지 (db 까는 것 제외), 아니면 아직 구현되지 않은 기능인지 확인 부탁드립니다.

+ 실사 중인 레포지트리: https://github.com/JeonDohyeon/imitated-seed
+ 실사 중인 사이트(어차피 반달해도 db 날리고 다시 셋팅하면 되는 거라 상관 없음): http://wiki.jdh5968.pe.kr:8800

**Comment by gdl-blue** [comment]
관리자 계정으로 로그인하면 위에 십자가 버튼이 뜰 건데 거기서 그룹을 먼저 추가하십시오.

**Comment by JeonDohyeon** [comment]
나무위키 옵션 켜져있을 때(맞나) `perm:aclgroup`이 별도로 있는 걸 까먹고 있었네요. 확인해서 조치했습니다.

**Comment by gdl-blue** [comment]
링크로 들어갔는데 ACL그룹이 아직 없는 것 같은데요.

![image](https://user-images.githubusercontent.com/55873929/195855614-0a6bcb04-18e3-4621-9e49-9d048a795d27.png)

먼저 권한 부여에서 aclgroup을 부여하시고,

![image](https://user-images.githubusercontent.com/55873929/195855760-b9b0fdfe-8ca8-4101-be1b-3c9233eb7cf6.png)

십자가 단추를 눌러서

![image](https://user-images.githubusercontent.com/55873929/195855847-42b6691b-65de-4312-b68a-ad2f900b3c68.png)

ACL그룹 이름을 적어 주시면

![image](https://user-images.githubusercontent.com/55873929/195855961-69b37af5-e202-4a12-ba38-6cb54a0cf737.png)

사용하실 수 있습니다.

**Comment by gdl-blue** [comment]
링크로 들어갔는데 ACL그룹이 아직 없는 것 같은데요.

![image](https://user-images.githubusercontent.com/55873929/195856330-b1b4fb0d-8445-4bf6-bb2e-876a8c9f0c0b.png)

먼저 권한 부여에서 aclgroup을 부여하시고,

![image](https://user-images.githubusercontent.com/55873929/195855760-b9b0fdfe-8ca8-4101-be1b-3c9233eb7cf6.png)

십자가 단추를 눌러서

![image](https://user-images.githubusercontent.com/55873929/195855847-42b6691b-65de-4312-b68a-ad2f900b3c68.png)

ACL그룹 이름을 적어 주시면

![image](https://user-images.githubusercontent.com/55873929/195855961-69b37af5-e202-4a12-ba38-6cb54a0cf737.png)

사용하실 수 있습니다.

**Comment by JeonDohyeon** [comment]
사실 테스트하다 서버 터져서..ㅋㅋㅋ
