### ISSUE TITLE
버려진 겁니까?

### ISSUE THREAD

**Issue by solutionwiki** [gdl-blue/imitated-seed-2#260]
아니 거의 한 달째 개발이 안 되네요..

**Comment by wikiengine** [comment]
개발자분 바쁘신거는 잊으시고 개발하기만 원하시는건 좀 아닌거같습니다

**Comment by navyCarpet** [comment]
개발자가 이전부터 개인적인 일 때문에 집중적인 개발은 어렵다고 여러 번 밝혔었는데 왜 자꾸 이런 이슈를 올리는지 모르겠네요
코드가 비공개인 것도 아니고, 코드가 npm package처럼 어려운 것도 아닌데 개발자가 개발을 못하는게 불만이면 본인이 PR을 올려서 개발해도 되는거 아닌가요?
