### ISSUE TITLE
토론 삭제 방법

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#261]
위키에 토론문재로 위키에 접근이 안되어 서버에서 물리적으로 삭제하련는데 방법 아시는분 있을까요?

**Comment by somewikiuser** [comment]
sqlite3 wikidata.db
그 이후는 sqlite3 사용방법 찾아보셔서 직접 하시면 됩니다

**Comment by somewikiuser** [comment]
아니면 그냥 토론 삭제 주소를 복사하시고 해당 토론 주소를 복사하신 다음 넣으시고 그 토론에 들어가시기 전 로그인하신 후 붙여넣기하고 들어가셔도 되고

**Comment by yoojinwoo123** [comment]
감사합니다
