### ISSUE TITLE
버그인지는 모르겠내요.

### ISSUE THREAD

**Issue by yoojinwoo12** [gdl-blue/imitated-seed-2#268]
차단기간 만료후 취소선이 없어지지 않습니다.
![Screenshot_20240511_083242_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/c433dde6-fca7-4781-b511-ef51aa8ecd0f)
![Screenshot_20240511_083237_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/161662484/2f9f62b8-1490-49bb-8a23-a4f40a8b746e)

**Comment by NOAH01112** [comment]
위키 소유자입니다. 안그럽니다.
