### ISSUE TITLE
[보안 취약점] 삭제됨

### ISSUE THREAD

**Issue by uiovasot** [gdl-blue/imitated-seed-2#272]
삭제됨

**Comment by uiovasot** [comment]
하늘위키도 마찬가지입니다.
![2024-06-07_16-10](https://github.com/gdl-blue/imitated-seed-2/assets/162868696/8a8c3390-7948-4388-8372-856e8cbcb286)

**Comment by uiovasot** [comment]
아니 관리자 권한까지 되네요

**Comment by uiovasot** [comment]
!!!

**Comment by uiovasot** [comment]
.

**Comment by uiovasot** [comment]
.

**Comment by uiovasot** [comment]
악용 가능성으로 내용을 삭제했습니다
임시 해결책: https://github.com/gdl-blue/imitated-seed-2/pull/274

**Comment by 1392-github** [comment]
내용 알려주세요
