### ISSUE TITLE
실행 오류

### ISSUE THREAD

**Issue by angelmini** [gdl-blue/imitated-seed-2#28]
NPM 스크립트 에서 Start 를 누루면 아래 와 같은 오류코드 가 떠 문의 드립니다. 
 *  작업 실행 중: npm run start 

> imitated-seed-v2@4.12.0 start
> node server

http://localhost/에서 실행 중. . .
node:events:368
      throw er; // Unhandled 'error' event    
      ^

Error: getaddrinfo ENOTFOUND http://localhost/
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:개인정보상 삭제함)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:개인정보상 삭제함)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:개인정보상 삭제함) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http://localhost/'
}

코딩 프로그램은 Visual Studio Code 호스팅 은 ngrok 을 사용중 입니다. 다운로드 받고 바로 와 나와있는되로 https://theseed.io/js/theseed.js 등을 추가 해도 똑같은 실행 오류가 일어납니다.

**Comment by poiega** [comment]
혹시 80 포트를 사용중인가요? 그럼 안됩니다. 3000포트나 이런걸로 해보세요. 아 그리고 ngrok 구동할때 3000포트로 열면
ngrok http 3000으로 하셔야합니다.

**Comment by gdl-blue** [comment]
서버 주소를 아이피 주소로 하십시오

**Comment by gdl-blue** [comment]
서버 주소를 127.0.0.1으로 하시면 됩니다
