### ISSUE TITLE
DB안에서 IP,UA가 암호화가 되야합니다

### ISSUE THREAD

**Issue by jinheyopp123** [gdl-blue/imitated-seed-2#284]
글리치는 DB가 노출되기도 하고 누가 맘만 먹으면 DB파일을 입수해 유출가능성이 있기때문에 DB에도 아이피와 UA는 암호화하는거 부탁드립니다

**Comment by NOAH01112** [comment]
그게 암호화되면 로그인 기록 조회할때 그걸 어떻게 불러올까요..?

**Comment by jinheyopp123** [comment]
음.... 그런가

**Comment by NOAH01112** [comment]
암호화할때 sha3로 암호화하는데 그건 해독할 수가 없습니다

**Comment by NOAH01112** [comment]
그렇다고 해독할수 있는 걸로 암호화하면 db 털리면 해독하면 되기 때문에 소용이 없죠

**Comment by jinheyopp123** [comment]
음..... 그것까진 예상못했네요 닫습니다
