### ISSUE TITLE
[나무위키 전용 기능] 편집 요청에만 추가적으로 표시되는 문구를 설정하게 할 수 있나요?

### ISSUE THREAD

**Issue by JeonDohyeon** [gdl-blue/imitated-seed-2#29]
다른 더시드 기반 위키는 안 그런데, 나무위키엔 편집 요청에만 표시되는 별도의 문구를 지정하고 있습니다.
[![예제](https://user-images.githubusercontent.com/34373595/197655759-69146a33-8ea9-4724-b650-f0589720ef30.png)](https://namu.wiki/new_edit_request/위키)
편집 요청이 추가된 지 얼마 안 되었을 때부터 추가된 것으로 보이는데, 이를 설정하게 할 수 있나요?

**Comment by aploga** [comment]
아니요. 새로 개발해야 합니다.

**Comment by poiega** [comment]
https://github.com/poiega/PoipoEngine/commit/627f43f9edcd61e7e6c7248ee85b570a0551b0d5 
제가 잘 수정한진 모르겠네요. 
이 엔진 4208줄을 수동으로 수정하시면 됩니다.

**Comment by gdl-blue** [comment]
나중에 만들어 보겠습니다
