### ISSUE TITLE
주석 파싱 문제

### ISSUE THREAD

**Issue by JeonDohyeon** [gdl-blue/imitated-seed-2#31]
나무마크를 이용해 문서를 작성하다 보면 주석을 많이 달 수밖에 없는데, 주석이 한두 개밖에 파싱되지 않고 나머지는 inline에 그대로 노출됩니다.
(Node 버전 문제일 경우 제 탓을 하시면 됩니다. 애초에 Node 18로 돌리고 있어서 18같은 일이 좀 많이 벌어질 거 같..ㅋㅋㅋ (찡긋))
[Node 버전 안 맞춘 문제의 바로 그 브랜치](https://github.com/JeonDohyeon/imitated-seed/tree/flight)

[주석 3개 달린 문서](https://wiki.jdh5968.pe.kr/w/개발일지:메인%20소스)([RAW](https://wiki.jdh5968.pe.kr/raw/개발일지:메인%20소스))

마크다운에서 \`text\` (`text`)에 해당하는 `{{{` `}}}` 매크로와 관련 고급 문법(HTML:리치 텍스트)까지 다함께 짬뽕돼있는 문서까지 여기다 링크 달아둡니다.
> 이 문서는 원래 주석도 겁나 많은데 얘도 주석 하나만 파싱되고 있습니다. `@related` #14 
> 얘는 숨긴 목차 문법이나 다크모드 문법까지 모두 다 들어가 있는 놈이라 어떻게 될진 몰?루

~~나무위키에서 경고 먹었던~~ [왠만한 문법 다 짬뽕돼있는 구 사용자 문서 백업](https://wiki.jdh5968.pe.kr/w/사용자:jdh5968/테스트)([RAW](https://wiki.jdh5968.pe.kr/raw/사용자:jdh5968/테스트))

**Comment by aploga** [comment]
파서 문제인듯 하나 노드 버전을 12로 낮춰보세요

**Comment by JeonDohyeon** [comment]
> 파서 문제인듯 하나 노드 버전을 12로 낮춰보세요

![image](https://user-images.githubusercontent.com/34373595/199462662-ee794d42-7dcd-454e-be5d-7d294f107ace.png)
node 버전 낮췄습니다.
![image](https://user-images.githubusercontent.com/34373595/199463161-412cbced-c4c2-4171-a3ac-1ed5a8d5d87d.png)
여전히 각주 고장나있습니다.

**Comment by aploga** [comment]
파서 문제가 맞는 듯 합니다. 다만 지금 개발자분이 잠수라 저희가 해결해야 할 문제인 듯 합니다. 곧 수정해서 PR 넣어보겠습니다(제 기술 안에서는 불가능할 가능성 있습니다)

**Comment by gdl-blue** [comment]
일단 알겠습니다. 나중에 고쳐보겠습니다

**Comment by gdl-blue** [comment]
'주석'은 편집 창에만 보이는 메모고, '주석'이 아니라 '각주'를 말씁하시는 것 같은데, 더시드엔진에서 파싱하는 방법을 제대로 파악하지 못해서 아직 제대로 구현하지 못했습니다.

**Comment by gdl-blue** [comment]
해결했습니다
