### ISSUE TITLE
goormide에 정확히 어떻게 설치 하는 간가요?

### ISSUE THREAD

**Issue by Gwangmayo** [gdl-blue/imitated-seed-2#36]
위키를 본 엔진으로 열기 위해 시도 중인데 호스팅은 goormide을 쓰고 있어요.
근데 계속 실패를 합니다. goormide는 애초에 sqlite3를 어떻게 세팅하는지 나와있는 정보도 없고
''css, js 디렉토리를 만든다.
https://theseed.io/js/theseed.js, https://theseed.io/js/jquery-2.1.4.min.js, https://theseed.io/js/jquery-1.11.3.min.js, https://theseed.io/js/intersection-observer.js, https://theseed.io/js/dateformatter.js )를 각각 다운로드받아 js 디렉토리에 복사한다.
https://theseed.io/css/wiki.css, https://theseed.io/css/katex.min.css, https://theseed.io/css/diffview.css )를 각각 다운로드받아 css 디렉토리에 복사한다.'' 에서도 저것들을 다운로드 받을 수 도 없어서 코드 복사 해서 붙여 넣어 보면 한 줄에 전부 작성 되어 맞는지도 모르겠구요. 도대체 어떻게 다운 받으며 엔진을 실행 시키는지 자세하게 알려주실 수 있나요?

**Comment by Gwangmayo** [comment]
아 되었네요 감사합니다!

**Comment by Gwangmayo** [comment]
회원가입을 하면 사유자 권한을 가진 계정이 생성 되는 것인가요?

**Comment by ontiger** [comment]
네. 처음 가입한 사용자에게 모든 권한이 부여됩니다.

**Comment by Gwangmayo** [comment]
인증 메일이 안오는건 왜 그런가요..?

**Comment by Gwangmayo** [comment]
스팸에도 존재 하지 않아요.,

**Comment by ontiger** [comment]
이메일 구현 안됐습니다.
