### ISSUE TITLE
회원가입 인증 메일 이 오지 않아요.

### ISSUE THREAD

**Issue by Gwangmayo** [gdl-blue/imitated-seed-2#37]
회원가입 인증 메일이 오지 않아요.. 스팸 메일함 에도 없어요.

**Comment by ontiger** [comment]
이메일 미구현 입니다.

**Comment by Gwangmayo** [comment]
지금 그거 때문에 회원가입 못하고 있는데 어떻게 끄나요..?

**Comment by ontiger** [comment]
@Gwangmayo 
## config.json
- config.json 수정으로 숨겨진 설정을 제어할 수 있다.
  - **`disable_email`: (기본값 false) 전자우편 인증을 끈다.**
  - `disable_login_history`: (기본값 false) 로그인 내역을 기록하지 않게 한다.
 ...

**Comment by Gwangmayo** [comment]
![image](https://user-images.githubusercontent.com/119497129/205042534-5f473936-4313-46fa-b559-910c906ad8b0.png)
들어가면 이거 뿐이에요

**Comment by Gwangmayo** [comment]
완료 되었네요. 감사합니다.

**Comment by ontiger** [comment]
그렇다면 Issue를 Close 해 주세요.
