### ISSUE TITLE
새 테섭 열었습니다.

### ISSUE THREAD

**Issue by ontiger** [gdl-blue/imitated-seed-2#39]
제가 개발자님도 아니고 이슈에 올릴 사안도 아닙니다. 다만 Discussion도 막혀 있고 알릴 곳이 이곳밖에 없네요.
PR(#38)에서 밝혔듯이 개발자님이 지금 테섭에 아무런 관심도 없으십니다. 하지만 테스트 서버는 다른 이용자들이 문법을 연습하고 권한을 연습할 수 있는 유일한 창구입니다. 바로 바로 수정사항을 볼 수 있기 때문에 개발에도 큰 도움이 되고요.
위의 이유들 때문에 새로 팠습니다. 주소는 [https://theseed.glitch.me](https://theseed.glitch.me) 입니다.

**Comment by gdl-blue** [comment]
아... 최근에 다른 일들 떄문에 개발할 시간이 부족하기도 하고, 구름 IDE가 무료 사용자에 대한 '항상 켜 두기' 기능을 다시 빼 버려서 운영이 어렵게 됐습니다. 새로 시험 서버 열어주신 건 감사드립니다.
