### ISSUE TITLE
문서가 존재 하지 않을 시

### ISSUE THREAD

**Issue by Gwangmayo** [gdl-blue/imitated-seed-2#42]
존재 하지 않은 문서를 검색 하면 아래와 같이 뜹니다.
이거 왜 이럴까요? 
![image](https://user-images.githubusercontent.com/119497129/206853952-e68e8625-67de-45e5-8604-575631a86a58.png)

**Comment by capiox** [comment]
Turn on your search engine and try again after restarting.

**Comment by gdl-blue** [comment]
검색 엔진을 켜주세용
