### ISSUE TITLE
테스트 서버 에러

### ISSUE THREAD

**Issue by ontiger** [gdl-blue/imitated-seed-2#43]
![image](https://user-images.githubusercontent.com/118987260/206855598-f613d6f7-8b02-4696-affc-b44a014b2df7.png)
제가 git pull로 해서 해시들 남겨진 것 때문에 좀 고생했습니다만, 그것때문일까요?
참고 - https://glitch.com/edit/#!/theseed

**Comment by ontiger** [comment]
지금은 해결했습니다. 램이나 CPU 문제였을 듯 하네요.

**Comment by ontiger** [comment]
바로 재발(....)
Status는 문제 없었습니다.

**Comment by ontiger** [comment]
git clonse으로 업뎃하니 문제 없음. git 문제였던 듯

**Comment by gdl-blue** [comment]
잠시만요

**Comment by gdl-blue** [comment]
방금 수정한 코드로 다시 해보십시오.
