### ISSUE TITLE
지금 테스트 서버가 둘다 작동 안하는데 이거라도 임의로 사용하실레요?

### ISSUE THREAD

**Issue by angelmini** [gdl-blue/imitated-seed-2#47]
지금 구름으로 연거와 글리치로 연거 둘다 테스트 서버가 접속이 안돼요. 근데 글리치로 여신분 말씀 처럼 테스트 서버는 정말 위키 엔진을 사용하는 이용자 또는 위키 사용자 입장에서 정말 중요해요. 그래서 이건 원래 제가 imitated-seed-2 엔진을 포크한 엔진 테스트위키 인데 별로 아직 안만져서 동일해요. 그래서 이거라도 일단 임시로 테스트위키로 사용하시면 어떨까 싶어요.
참고로 저 테스트위키 서버는 유료호스팅 이라 터질 걱정은 딱히 안하셔도 되요.
일단 테스트위키 주소는 이거에요 https://yurawiki.ga/

**Comment by gdl-blue** [comment]
로그인 기록이 남나요?

**Comment by angelmini** [comment]
로그인 기록은 남아요.

**Comment by angelmini** [comment]
gdl-blue님 확정 답변 받으면 스레드라 해야 할까요 일단 이거 닫을게요
