### ISSUE TITLE
궁금한게 있습니다.

### ISSUE THREAD

**Issue by RUASHIA** [gdl-blue/imitated-seed-2#52]
goormide에서 항상 켜짐 가능하게 플렌을 변경하고 항상 켜짐을 활성화 시킨 다음 nohup node server 또는 nohup node server & 로 엔진을 실행 시켰지만 구름을 브라우저에서 끄면 엔진도 같이 꺼집니다. 해결 방법이 있다면 알려주세요

**Comment by yopu1230** [comment]
npm을 사용해 보세요.

**Comment by RUASHIA** [comment]
엇 감사합니다!
