### ISSUE TITLE
glitch로 서버 어떻게 여는 건가요?

### ISSUE THREAD

**Issue by RUASHIA** [gdl-blue/imitated-seed-2#53]
최대한 혼자서 해 볼려고 했는데 glitch가 딱히 강의도 없어서 도대체  프로젝트를 여떻게 열고 서버를 어케 열고 등등.. glitch로 위키 여는 방법 쫌 알려주실 수 있나요..?

**Comment by nawega** [comment]
1. gitch 가입
 2. glitch 새 프로젝트 생성
     이때, git을 이용해 생성(https://github.com/gdl-blue/imitated-seed-2.git)
 3. glitch에 들어가 터미널 접속
 4. 아래 명령어 순차적으로 입력
 ```
npm i
node server(질문에 답하세요.)
refresh
killall -2 node
node server
 ```

**Comment by RUASHIA** [comment]
https://glitch.com/edit/#!/minblewiki
보시면 알겠지만 config.json 파일이 보이지 않습니다..

**Comment by nawega** [comment]
> https://glitch.com/edit/#!/minblewiki 보시면 알겠지만 config.json 파일이 보이지 않습니다..

언급한대로 ,```npm i``` 입력 후 ```node server```를 입력하세요. 그럼 몇가지를 물어볼텐데, 거기에 답하면 config.json이 생성됩니다.

**Comment by RUASHIA** [comment]
그렇게 해서 위키까지 정상적으로 열었는 데 안 보이는 겁니다.

**Comment by nawega** [comment]
> 그렇게 해서 위키까지 정상적으로 열었는 데 안 보이는 겁니다.

.gitignore을 확인해주세요

**Comment by RUASHIA** [comment]
> > 그렇게 해서 위키까지 정상적으로 열었는 데 안 보이는 겁니다.
> 
> .gitignore을 확인해주세요

node_modules/
skins/
wikidata.db
config.json
node.exe
js/
!js/banana.js
css/

라고 하네요. 있긴 한가 봅니다.

**Comment by nawega** [comment]
> 

거기서 config.json을 빼시면 보일겁니다.

**Comment by RUASHIA** [comment]
혹시 한가지 만 더 물어보자면 이거 원래 있던 DB를 글리치로 연 위키에 어떻게 이전 시키나요..?

**Comment by nawega** [comment]
> 혹시 한가지 만 더 물어보자면 이거 원래 있던 DB를 글리치로 연 위키에 어떻게 이전 시키나요..?

 1. wikidata.db 다운로드
 2. 글리치에 드래그해서 업로드
 3. Glitch CDN에 업로드 된 것을 wget으로 받아오고 이름 바꾸기
