### ISSUE TITLE
그래서 이건 버려진겁니까?

### ISSUE THREAD

**Issue by nawega** [gdl-blue/imitated-seed-2#55]
할일 잔뜩 쌓였습니다. 정 안되면 저나 fafa님께 토스하시든지요

**Comment by cuprevenge** [comment]
포크하셔서 개발을 이어가면 되지 않을까요.

**Comment by nawega** [comment]
> 포크하셔서 개발을 이어가면 되지 않을까요.

포크를 해도 원본에서 PR을 안받아주면 유명무실합니다...

**Comment by nawega** [comment]
그리고 원 개발자만큼 코드를 잘 아는 사람이 없습니다. 이정도 규모면 거의 코드를 외워야 해서요.
