### ISSUE TITLE
개선 요청

### ISSUE THREAD

**Issue by Roselia31** [gdl-blue/imitated-seed-2#62]
현재 엔진은 위키 소유자도 권한 회수 및 로그인 기록 조회가 된다는 문제가 있습니다. 그리하여 소유자 메뉴에서 권한 부여 또는 회수가 가능하거나 애초에 소유자는 권한 및 로그인 기록 조회가 되지 않았음 합니다. 또, no_force_recaptcha 권한을 소유하면 리캡챠가 나오지 않으면 어떨까 싶습니다. 또 소유자가 하루에 한 사용자가 개설할 수 있는 토론 개수를 지정할 수 있으면 좋겠습니다.(토론 도배 방지) 또 스레드에서 댓글 작성 쿨타임(예: 1개의 댓글을 작성시 10초 후 작성 가능)이 있음 합니다.
이 모든건 제가 위키 운영 및 관리자로 활동하며 발견한 해당 엔진에 취약점 입니다.

**Comment by gdl-blue** [comment]
권한 및 로그인 내역 개선 적용은 config.json에서 `protect_owners`를 true로 설정하십시오

**Comment by gdl-blue** [comment]
캡챠 무시는 반영했습니다

**Comment by gdl-blue** [comment]
토론 도배는 더 시드 엔진에도 똑같이 있을 것 같긴 한데 구현은 해보겠습니다

**Comment by kepitrion** [comment]
이 엔진에 캡챠가 존재했나요?

**Comment by gdl-blue** [comment]
네

**Comment by gdl-blue** [comment]
config.json에서 `enable_captcha`를 true로 하시면 됩니다

**Comment by Roselia31** [comment]
그리고 혹시 나무마크 업데이트하고 이미지 업로드 가능하게 해주실 수 있나요?

**Comment by Roselia31** [comment]
그리고 가능하다면 오픈나무하고 문서는 DB 연동되었으면 좋겠네요
