### ISSUE TITLE
업데이트 질문

### ISSUE THREAD

**Issue by roselia2023** [gdl-blue/imitated-seed-2#63]
혹시 글리치에서 해당 엔진을 어떻게 업데이트 하나요?

**Comment by theseeduser** [comment]
저는 업데이트된 파일을 복사하여 기존 내용을 지우고 붙여넣기 하는 방법으로 했습니다.

**Comment by gdl-blue** [comment]
자체 업데이트 기능은 아직 없어서 위 방법대로 하시면 됩니다
