### ISSUE TITLE
최근 토론 오류

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#64]
(node:185) UnhandledPromiseRejectionWarning: ReferenceError: minor is not defined5:33 PM

Jump Toat recentDicsuss (eval at <anonymous> (/app/routes/router.js:27:5), <anonymous>:59:91)5:33 PM

(node:185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)5:33 PM

이 오류가 발생하면 기다리거나 refresh를 해도 문제가 해결되지 않아서 도메인을 바꾸고 위키를 다시 설치해야 합니다. 빠른 해결 부탁드립니다.

**Comment by theseeduser** [comment]
오류로 인해 최근 토론 접속이 불가능해 불편합니다.

**Comment by gdl-blue** [comment]
수정 완료
