### ISSUE TITLE
업데이트 후 버그

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#65]
https://wiki2.pythonanywhere.com/w/file:imitated%20seed%20%EC%B5%9C%EA%B7%BC%20%ED%86%A0%EB%A1%A0%20%EB%B2%84%EA%B7%B8.jpg

위 사진과 같이 토론과 편집 요청이 같이 표시됩니다.

추가로, 테스트 서버 주소 https://quill-brawny-belt.glitch.me 으로 변경 부탁드려요.

**Comment by gdl-blue** [comment]
그건 버그는 아니고 더시드 엔진 구 버전에서 그랬습니다만 신 버전에선 토론만 나오는 게 맞아서 곧 수정해보겠습니다

**Comment by gdl-blue** [comment]
https://board.namu.wiki/b/free/2277496

요구 theseed_version은 시기로 봐서 4.18.1로 하겠습니다

**Comment by gdl-blue** [comment]
완료
