### ISSUE TITLE
검색 엔진 버그

### ISSUE THREAD

**Issue by Roselia31** [gdl-blue/imitated-seed-2#66]
존재하지 않는 문서를 검색하면 로딩이되지 않는 버그가 있습니다.

**Comment by gdl-blue** [comment]
오류 로그를 보여주실 수 있습니까?

**Comment by roselia2023** [comment]
![image](https://github.com/gdl-blue/imitated-seed-2/assets/114271599/47a9e507-6087-4652-938b-f245d1b3991d)
이렇게만 뜨는데 저 오류 코드는 스킨 오류 코드 같아서 아닌거 같긴 합니다

**Comment by roselia2023** [comment]
이건 스킨 오류 같기는 합니다만.. 콘솔에 뜨는 오류는 저거 뿐입니다

**Comment by gdl-blue** [comment]
검색 서버 풀그림 문제 같습니다만 좀 더 확인해봐야 할 것 같습니다

**Comment by gdl-blue** [comment]
짐작가는 것 수정했습니다. 확인해주십시오

**Comment by Roselia31** [comment]
정상 작동하네요. 감사합니다.
