### ISSUE TITLE
엔진 공식 리버티로 사용 건의

### ISSUE THREAD

**Issue by roselia2023** [gdl-blue/imitated-seed-2#67]
현 the seed 엔진과 비슷하게 리버티를 커스텀하였습니다. 그리하여 개발자님만 괜찮다면 이 스킨을 해당 엔진 공식 스킨으로 사용하였음 합니다.
[해당 Liberty](https://github.com/COVERTIV/Liberty-skin)

**Comment by navyCarpet** [comment]
개인적으로 봤을 때 문제가 많은 코드로 보입니다.

https://github.com/COVERTIV/Liberty-skin/commit/bbdaf39fc4f08b26995ba5cc1b10b4b16b739a9d

**Comment by roselia2023** [comment]
혹시 보완을 위해 어떤 부분이 문제인지 알려주실 수 있나요?

**Comment by roselia2023** [comment]
아 아이피 출력해주는 스크립트가 잘못하면 오류를 내는 군요. 그러면 그 부분 보완 후 다시 올리겠습니다

**Comment by gdl-blue** [comment]
그냥 `{{ req_ip }}`로 하시면 됩니다
