### ISSUE TITLE
차단된 아이피 ACL 표시 버전 수정 요청

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#69]
IPACL 기능이 4.18.0에 사라졌는데 차단된 아이피 옵션은 아직 있습니다. 수정 부탁드립니다.

**Comment by theseeduser** [comment]
2017년 이전 ACL 항목 중 관리자가 괸리자로 표시되어있습니다. 그리고 코드 메인 화면에 block_history는 왜 있는건가요?

**Comment by gdl-blue** [comment]
수정했습니다

> 그리고 코드 메인 화면에 block_history는 왜 있는건가요?

무슨 말씀이신가요?

**Comment by theseeduser** [comment]
https://wiki2.pythonanywhere.com/w/file:imitated%20seed%202.jpg

routes 폴더 안에 있어야 할 파일이 폴더 밖에 있습니다.

**Comment by gdl-blue** [comment]
고쳤습니다
