### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by roselia2023** [gdl-blue/imitated-seed-2#72]
아래 사진 처럼 사용자 토론이 있는 상태에서 그 사용자 토론을 close로 바꾸지 않고 바로 삭제하면 계속 현재 진행중인 사용자 토론이 있습니다.라고 뜹니다.
![image](https://github.com/gdl-blue/imitated-seed-2/assets/114271599/37dc949f-5bc0-4c1a-8d37-5b5f67c53a5d)

**Comment by gdl-blue** [comment]
수정했는데 확인해보십시오

**Comment by roselia2023** [comment]
수정되었습니다. 스레드 닫겠습니다.
