### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#73]
1. 특수 권한 틀과 차단 틀이 글자가 너무 큽니다. (11pt 정도가 적당할것 같습니다)
2. 스레드 상태 변경 등이 쓰레드 상태 변경으로 되어 있습니다.
3. 차단된 사용자는 문서, 토론 모두 회색 닉네임에 취소선이 있으면 더 알아보기 편할 것 같습니다.
4. 스레드 주제 변경, 스레드 이동 기능이 없던 the seed 버전에서 주제 변경과 이동 권한이 남아있습니다.
5. 사용자 이름을 클릭했을 때 더시드처럼 기여내역, 사용자 문서, 차단 버튼(빠른 ACLGroup)이 표시되면 좋겠습니다.
6. 더시드위키에서 테스트한 결과, ACLGroup 권한이 없고 admin 권한만 있어도 ACLGroup에서 차단된 사용자에 사용자 추가/삭제는 가능했습니다. 이 부분은 5번에도 반영 부탁드립니다. (그룹 추가/삭제나 로그인 허용 차단 등 다른 그룹에는 추가/삭제가 불가능합니다.)

감사합니다.

**Comment by roselia2023** [comment]
5번은 빠른 ACL Group 말씀하시나 보군요

**Comment by gdl-blue** [comment]
1. http://web.archive.org/web/20181119130358/https://theseed.io/w/%EC%82%AC%EC%9A%A9%EC%9E%90:namu (원하시면 바꾸겠습니다)
2. https://namu.wiki/w/%ED%8C%8C%EC%9D%BC:e92775_%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202018-02-01%20%EC%98%A4%EC%A0%84%2012.29.19.png?rev=1 (원하시면 바꾸겠습니다)
3. 원하신다면 바로 추가하겠습니다만 원래 Nuxt.js 프론트엔드 기능입니다
4. 수정하겠습니다
5. 원하신다면 바로 추가하겠습니다만 원래 Nuxt.js 프론트엔드 기능입니다
6. 수정하겠습니다

일단 구버전과 신버전의 UI/문구 차이는 나중에 Nuxt.js 프론트엔드 만들 때 전부 고칠 예정입니다

**Comment by theseeduser** [comment]
구버전 the seed에서 없던 기능은 해당 버전의 상위 버전만 가능하게 하고 원할한 테스트 및 운영을 위해 적혀 있는 모든 기능 추가 및 수정 요청드려요.

**Comment by theseeduser** [comment]
6번이 완전히 적용되지 않았습니다. aclgroup 권한을 회수 했을 때 aclgroup 메인 화면에서 차단된 사용자 그룹이 표시되지 않으며 URL로 접속해서 테스트한 결과 차단된 사용자 그룹에서 사용자 삭제가 불가능합니다.

**Comment by roselia2023** [comment]
빠른 ACL Group이 있는거와 없는거에 업무 처리 속도가 달라지긴 해요. 그래서 전 있으면 좋다고 생각해요.

**Comment by gdl-blue** [comment]
> 6번이 완전히 적용되지 않았습니다. aclgroup 권한을 회수 했을 때 aclgroup 메인 화면에서 차단된 사용자 그룹이 표시되지 않으며 URL로 접속해서 테스트한 결과 차단된 사용자 그룹에서 사용자 삭제가 불가능합니다.

admin과 aclgroup 권한이 같이 있어야 되는 것은 아닌가요?

**Comment by gdl-blue** [comment]
> 빠른 ACL Group이 있는거와 없는거에 업무 처리 속도가 달라지긴 해요. 그래서 전 있으면 좋다고 생각해요.

나무픽스에 빠른 사용자 차단이 있긴 한데 ACL그룹과는 호환이 안 돼서 구현은 해보겠습니다

**Comment by theseeduser** [comment]
https://theseed.io/BlockHistory?query=theseeduser&target=text

aclgroup 권한을 받기 전 admin 권한만 있을때 셀프 차단이 가능했습니다. aclgroup 권한이 없으면 ACLGroup 메뉴에서 삭제(x) 버튼이 없고 차단된 사용자 이외의 그룹에선 추가 버튼, 삭제 버튼이 선명한 색이 아니게 표시되고 클릭이 불가합니다.

**Comment by gdl-blue** [comment]
수정했습니다

**Comment by theseeduser** [comment]
추가

6. 'admin 권한만 있을때도 ACLGroup 메인 페이지에서 차단된 사용자 그룹 접근 가능' 이 적용되지 않았습니다.
7. 최신 더 시드 버전을 선택했을 경우 편집 권한이 없을 때 편집 요청으로 자동으로 넘어가는 기능 추가
8. 최신 더 시드 버전을 선택했을 경우 editble_other_user_document 권한 삭제 및 no_force_recaptcha 권한 이름을 no_force_captcha으로 변경
