### ISSUE TITLE
이메일 관련 질문

### ISSUE THREAD

**Issue by roselia2023** [gdl-blue/imitated-seed-2#76]
const transporter = nodemailer.createTransport({
  service: 'gmail',  // Gmail
  auth: {
    user: hostconfig.email ,  // 발송자 이메일
    pass: hostconfig.passwd,  // 발송자 이메일 비밀번호
  },
});
여기서 어디에 무엇을 넣어야 하는건가요?

**Comment by 24fw** [comment]
hostconfig.json파일에 `"email":"이메일 주소","passwd":"이메일 비번"`추가하시면 됩니다.
참고로 이메일은 지메일 사용하시고 비번은 구글 앱비밀번호 사용하십시오.
(지메일 사용안하신다면 말햐주세요)

**Comment by roselia2023** [comment]
감사합니다!
