### ISSUE TITLE
스킨 관련 질문

### ISSUE THREAD

**Issue by Roselia31** [gdl-blue/imitated-seed-2#77]
안녕하세요. imitated seed에 맞게 리버티 스킨을 개발 중인 Roselia라고 합니다. 다름이 아닌 질문이 있어 질문을 작성합니다. 편집창에서는 역링크 삭제 이동 만 뜨고, 역사창에서는 편집 역사 만 뜨게 어떻게 작업해야 할지 모르겠습니다. 두번째로 별찜을 누루는거 까지는 작업했는데 한번더 누르면 해체되게 어떻게 해야할지 모르겠습니다. 아시는 분은 답변해주시면 감사하겠습니다.

**Comment by gdl-blue** [comment]
스킨은 더시드엔진 (4.12.0 이하) 스킨 제작법과 완전히 같습니다

```
{% if skinInfo.viewName == 'edit' %}
<a href="...">역링크</a>
...
{% endif %}
{% if skinInfo.viewName == ['xref' %}
편집 링크
역사 링크
{% endif %}
```

별찜 해제
```
{% if starred %}
별찜 해제 링크
{% else %}
별찜하기 링크
{% endif %}
```

아이피 확인
```
{{ req_ip }}
```

**Comment by Roselia31** [comment]
감사합니다
