### ISSUE TITLE
나무마크 버그

### ISSUE THREAD

**Issue by Roselia31** [gdl-blue/imitated-seed-2#78]
![Screenshot_20230716_010710_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/114271599/05427e9f-dca3-46cd-ac5a-91305d6cb4f8)
HTML로 렌더링되는 걸로 보아 구현은 하신걸로 추측되어 버그 인듯 싶네요. 위 사진 나무마크는 이것입니다.
![Screenshot_20230716_010758_Chrome](https://github.com/gdl-blue/imitated-seed-2/assets/114271599/a5ddaba7-2789-4582-9280-b0b50ccc0b24)

**Comment by gdl-blue** [comment]
확인 부탁드리며, XSS 취약점이 생기는지 확인해야 할 것 같습니다

**Comment by 24fw** [comment]
#FFFFF를 #FFF로 바꿔보세요

**Comment by Roselia31** [comment]
해결되었습니다. 감사합니다.
