### ISSUE TITLE
특수 권한 틀 표시되지 않는 문제

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#80]
컴퓨터 localhost, 구름IDE 등에서 '이 사용자는 특수 권한을 가지고 있습니다.' 틀이 표시되지 않습니다.
그리고 구름에서 토론 댓글 로딩이 너무 오래걸리는데 해결 방법 있나요?

**Comment by gdl-blue** [comment]
> 컴퓨터 localhost, 구름IDE 등에서 '이 사용자는 특수 권한을 가지고 있습니다.' 틀이 표시되지 않습니다.

admin 권한을 부여하셨습니까?

> 그리고 구름에서 토론 댓글 로딩이 너무 오래걸리는데 해결 방법 있나요?

혹시 banana.js을 사용하신다면 다시 없애보십시오

**Comment by theseeduser** [comment]
1. 네
2. 활성화하는 방법을 모르는데 켜져 있지는 않은 것 같네요. 해당 파일 삭제해봤는데 속도는 비슷한 것 같습니다.

**Comment by gdl-blue** [comment]
멀티쓰레딩을 꺼도 그럽니까? (config.json에서 `disable_multithreading`를 참으로 변경)

**Comment by theseeduser** [comment]
멀티쓰레딩 끄는 기능 노트북에서 다시 시도해봤는데 잘 됩니다. 서버에서 오타가 있었던 것 같네요.

**Comment by theseeduser** [comment]
이
