### ISSUE TITLE
html 문법오류

### ISSUE THREAD

**Issue by 24fw** [gdl-blue/imitated-seed-2#82]
문법
![IMG_2728](https://github.com/gdl-blue/imitated-seed-2/assets/100505515/f5174de4-1dfb-4e64-a952-989e92618413)
결과
![IMG_2729](https://github.com/gdl-blue/imitated-seed-2/assets/100505515/d8c3279e-ecd4-4981-a8d2-096c8aa6fcc5)

**Comment by gdl-blue** [comment]
[40cd04c](https://github.com/gdl-blue/imitated-seed-2/commit/40cd04c59b0d1cb3ecc057a8d2f6eb4dd81e9487)

고쳐졌는지 확인해주십시오
