### ISSUE TITLE
업데이트 후 오류

### ISSUE THREAD

**Issue by theseeduser** [gdl-blue/imitated-seed-2#85]
테스트 서버 이메일 업데이트를 했는데 server.js에 unexpect token 이라고 오류가 떠서 해당 문구를 삭제했습니다. 그런데 그 이후로 위키 이름이 로드될때마다 사용자 지정(테스트위키) 에서 더 시드로 계속 바뀝니다. 지금은 사용자지정 이름공간에 테스트위키를 추가하는 방법으로 임시조치를 해 놓았습니다.
오류 서버: quill-brawny-belt.glitch.me

**Comment by 24fw** [comment]
routes/signup.js 2번째줄에있는 `, '더 시드'`를 지우시면 해결됩니다. pr도 올라와있네요.
